### PR TITLE
Ensure model updates include setter to avoid events bouncing

### LINKED ISSUE #83: The pan and zoom tools doesn't work well in widget mode
Here is the code:

```python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
import jupyter_bokeh as jb
import numpy as np

fig = figure(height=200, width=300)
x = np.linspace(0, 10, 200)
y = np.sin(x)
source = ColumnDataSource(data=dict(x=x, y=y))
line = fig.line("x", "y", source=source)
fig_w = jb.BokehModel(fig)
fig_w
```

and the response of the pan and zoom operations.

fig_widget

Here is the version info:

```
Windows 10, Chrome and Firefox

bokeh: 1.4.0
jupyter lab: 1.2.1
notebook: 6.0.1
jupyter_bokeh: 1.1.0
python: 3.7.3
```

the widget mode means communicate between bokehjs and python kernel through ipywidgets. 

Here is the example notebook:

https://github.com/bokeh/jupyter_bokeh/blob/master/examples/jupyter_widgets.ipynb

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes #83 

Would be good to release once this is merged.

Cc: @bryevdv and @mattpap

### CODE REVIEW

**Comment by philippjfr** [comment]
Also any chance I can be given push access to this repo?

**Comment by bryevdv** [comment]
check now? All the teams were set to read only access for some reason

**Comment by philippjfr** [comment]
That worked, thanks. This is ready to merge unless you can suggest a better approach.

**Comment by bryevdv** [comment]
LGTM

**Comment by bryevdv** [comment]
I don't actually know what the exact procedures to release the extension currently are. Those should really be documented. So I'll let @mattpap merge in case he wants to offer any comments before releasing.

**Pull request merged**
