### PR TITLE
v3.0.5, added support for ipywidgets>=8.0.0

### LINKED ISSUE #168: Does not work with the latest version of ipywidgets
`jupyter_bokeh` does not work with `ipywidgets >=8.0.0a0` Latest compatible version of ipywidgets is `7.7.2`.

### PR DESCRIPTION
**Pull request by axil**
Built upon v3.0.4.  Fixes #168

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks for looking at this. It looks good, but has to be rebased unfortunately.

**Comment by axil** [comment]
Well, technically speaking it should be trivial to rebase as it is just one bump in the dependencies:

  "dependencies": {
-    "@jupyter-widgets/base": "^3 || ^4.0.0",
+    "@jupyter-widgets/base": "^6",

Is the current main branch ready for release?

I've written an article about bokeh but I can't publish it because `pip install jupyter_bokeh` does not work.

**Comment by philippjfr** [comment]
@mattpap There's a few people asking for a release now. Any chance we could make this change and then release?

**Comment by axil** [comment]
@philippjfr I've rebased against main. Now it says "Can't find module core/serialization". Do you know how to deal with it?

**Comment by axil** [comment]
@philippjfr @mattpap maybe it is possible to release 3.0.5a alpha version without rebasing? And then gradually complete the serialization improvements? Because as of today jupyter_bokeh is not working at all because of the changes in ipywidgets (in v8.0.0).

**Comment by mattpap** [comment]
> Now it says "Can't find module core/serialization".

This is because `main` is updated for bokeh 3.0.

**Comment by philippjfr** [comment]
Would be nice if we could release a fix here before bokeh 3.0 though.

**Comment by mattpap** [comment]
> Would be nice if we could release a fix here before bokeh 3.0 though.

Sure. I will create a release branch off an earlier commit, merge and release, and then merge back to `main`.

**Comment by mattpap** [comment]
I rebase this and update lock files. @axil, make sure you use npm 8+, so that lock file version is not downgraded. Looks like everything works with bokeh 2.4.

**Pull request merged**
