### PR TITLE
Handle different session API in Voila

### LINKED ISSUE #106: Not working in Voila
So I haven't dug very deep yet but even the simplest example using the `BokehModel` not seem to render in Voila:

```python
from bokeh.plotting import figure, Row
from jupyter_bokeh import BokehModel

p = figure()
p.line([1, 2, 3], [1, 2, 3])

model = BokehModel(model=p)
model
```

```
voila notebook.ipynb
```

Screen Shot 2020-07-09 at 12 09 28 AM

bokeh 2.1.1
jupyter_bokeh 2.0.2 
voila 0.1.21

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes #106 

@mattpap Releasing after this is merged would be great but feel free to refactor it.

### CODE REVIEW

**Comment by mattpap** [comment]
I will get this released tomorrow.

**Comment by philippjfr** [comment]
Gentle ping 🙂

**Comment by mattpap** [comment]
I will refactor the entire module later, as there have too many `any`s slipped in recently.

**Comment by mattpap** [comment]
@philippjfr, 2.0.3 is published.

**Comment by philippjfr** [comment]
Thank you. Any suggestions on a pure Bokeh example to include in the voila gallery?

**Pull request merged**
