### PR TITLE
Add __version__ to python module

### PR DESCRIPTION
**Pull request by ceball**
I guess you might not want to merge this as is - I probably need to at least document this in some release doc or other? Or I could do something fancier if you prefer (e.g. add versioneer, as in bokeh).

### CODE REVIEW

**Comment by bryevdv** [comment]
@ceball there's not really currently any process around releases for this package yet. Ideally I think we would adopt the same use of versioneer as the main package. But this is probably a reasonable interim mesasure. 

cc @mattpap

**Comment by ceball** [comment]
I was debugging a problem with a particular installation, and in the process happened to notice the version was missing.

In fact, the problem itself actually turned out to be that the version in https://github.com/bokeh/jupyter_bokeh/blob/master/jupyter_bokeh/widgets.py#L43 is 1.1.0 (for the 1.1.1 release). (In this particular usage, it was looking for @bokeh/jupyter_bokeh@^1.1.0 from an internal unpkg - which happens to not exist, as only 1.1.1 has been added.)

**Comment by bryevdv** [comment]
@mattpap do you have any thoughts or prefs here? I guess I am +0.5 on adding versioneer. It's a bit heavyweight OTOH it also just works.

**Comment by bryevdv** [comment]
About to bump to 1.2

**Pull request closed without merging**
